name: libsignal-build

on:
  push:
    branches:
      - 'armv6'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

      - name: QEMU build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv6
          distro: bullseye
          #githubToken: ${{ github.token }} # Not required, but speeds up builds by storing container images in a GitHub package registry.
          run: |
            uname -a
            # Install required packages
            apt-get update && apt-get install -y git python3 g++ clang libclang-dev cmake make protobuf-compiler curl file
            # Install rust
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            rustup toolchain install nightly --profile minimal
            # Clone upstream source
            git clone https://github.com/signalapp/libsignal _repo_dir
            cd _repo_dir
            # Build
            RUSTFLAGS='-C link-arg=-s' RUST_BACKTRACE=1 cargo build --release --verbose
