name: libsignal-build

on:
  push:
    branches:
      - 'armv6'

jobs:

  build:

    runs-on: ubuntu-20.04

    env:
      TARGET: arm-unknown-linux-gnueabihf

    steps:

      - name: Clone upstream source
        uses: actions/checkout@v3
        with:
          repository: signalapp/libsignal
          ref: v0.22.2

      - name: Install Rust toolchain
        run: rustup toolchain install nightly --profile minimal

      - name: Install cross-rs
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: cross-rs config
        run: |
          cat >> Cross.toml <<EOF
          [build.env]
          passthrough = ["CC=arm-linux-gnueabihf-gcc", "CXX=arm-linux-gnueabihf-g++", "CPATH=/usr/arm-linux-gnueabihf/include"]
          EOF

      - name: cross-rs build
        run: |
          export RUSTFLAGS='-C link-arg=-s'
          export RUST_BACKTRACE=1
          cross build --target $TARGET --release --verbose
